generator:
  class: sfDoctrineGenerator
  param:
    model_class:           spPhoto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sp_photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des photos des diff√©rents sports
        display: [sport, _photo]
        object_actions:
          _delete: ~
      filter: ~
      form:
        class: spPhotoBackendForm
      edit: ~
      new:
        title: Ajouter une photo
